"""add telegram_id to candidate

Revision ID: d69c6f32980b
Revises: 
Create Date: 2025-11-21 11:51:21.973559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69c6f32980b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_analytics_candidate'))
        batch_op.drop_index(batch_op.f('idx_analytics_candidate_date'))
        batch_op.drop_index(batch_op.f('idx_analytics_date'))

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('bot_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bot_channels_bot'))
        batch_op.drop_index(batch_op.f('idx_bot_channels_candidate'))

    with op.batch_alter_table('bot_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bot_instances_active'))
        batch_op.drop_index(batch_op.f('idx_bot_instances_candidate'))

    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bot_users_telegram'))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('has_used_trial',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_candidates_active'))
        batch_op.drop_index(batch_op.f('idx_candidates_province'))
        batch_op.drop_index(batch_op.f('idx_candidates_username'))
        batch_op.create_foreign_key(None, 'candidates', ['referred_by'], ['id'])

    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_channel_stats_date'))

    with op.batch_alter_table('gamification_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('headquarters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_headquarters_candidate'))

    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_candidate'))
        batch_op.drop_index(batch_op.f('idx_messages_candidate_category'))
        batch_op.drop_index(batch_op.f('idx_messages_candidate_created'))
        batch_op.drop_index(batch_op.f('idx_messages_category'))
        batch_op.drop_index(batch_op.f('idx_messages_created'))
        batch_op.drop_index(batch_op.f('idx_messages_is_read'))
        batch_op.drop_index(batch_op.f('idx_messages_priority'))
        batch_op.drop_index(batch_op.f('idx_messages_sentiment'))

    with op.batch_alter_table('monthly_top_citizens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('awarded_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('plan_purchases', schema=None) as batch_op:
        batch_op.alter_column('is_trial',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('trial_used',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('admin_granted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_programs_candidate'))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_resumes_candidate'))

    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scheduled_posts_channel'))
        batch_op.drop_index(batch_op.f('idx_scheduled_posts_status'))
        batch_op.drop_index(batch_op.f('idx_scheduled_posts_time'))

    with op.batch_alter_table('slogans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_slogans_candidate'))

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('slogans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_slogans_candidate'), ['candidate_id'], unique=False)

    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_scheduled_posts_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_scheduled_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_scheduled_posts_channel'), ['channel_id'], unique=False)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_resumes_candidate'), ['candidate_id'], unique=False)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_programs_candidate'), ['candidate_id'], unique=False)

    with op.batch_alter_table('plan_purchases', schema=None) as batch_op:
        batch_op.alter_column('admin_granted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('trial_used',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_trial',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('monthly_top_citizens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('awarded_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_messages_sentiment'), ['sentiment_label'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_priority'), ['category_priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_is_read'), ['is_read', 'candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_candidate_created'), ['candidate_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_candidate_category'), ['candidate_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_candidate'), ['candidate_id'], unique=False)

    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('headquarters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_headquarters_candidate'), ['candidate_id'], unique=False)

    with op.batch_alter_table('gamification_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('description')

    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_channel_stats_date'), ['date'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_candidates_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_candidates_province'), ['province', 'city'], unique=False)
        batch_op.create_index(batch_op.f('idx_candidates_active'), ['is_active'], unique=False)
        batch_op.alter_column('has_used_trial',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('telegram_id')

    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bot_users_telegram'), ['telegram_id'], unique=False)

    with op.batch_alter_table('bot_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bot_instances_candidate'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_bot_instances_active'), ['is_active'], unique=False)

    with op.batch_alter_table('bot_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bot_channels_candidate'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_bot_channels_bot'), ['bot_instance_id'], unique=False)

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('condition_action')

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_analytics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('idx_analytics_candidate_date'), ['candidate_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_analytics_candidate'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###
